### ISSUE TITLE
Discussion: remove slurpy keyword args

### ISSUE THREAD

**Issue by jjl** [macchiato-framework/macchiato-fs#5]
I just took at peek at the macchiato.fs namespace and I see a lot of slurpy keyword args. These are more difficult to wrap than functions which just take an optional params map.

A recent discussion on clojure IRC led to a general concensus that slurpy keyword args were in general a code smell. I vote to change them to take an optional extra options map. Thoughts?

**Comment by yogthos** [comment]
The main reason for that was to keep consistent with Clojure slurp that uses keyword args.

**Comment by jjl** [comment]
Ah yes, that's true, I hadn't noticed it was just for spit and slurp.

Hrm, doing it right or copying clojure? Tough call...
