### ISSUE TITLE
WARNING: resolve already refers to: cljs.core/resolve being replaced by: macchiato.fs.path/resolve

### ISSUE THREAD

**Issue by kommen** [macchiato-framework/macchiato-fs#9]
Since upgrading to ClojureScript 1.9.660 I get the following warning when compiling our app with macchiato-fs:
> WARNING: resolve already refers to: cljs.core/resolve being replaced by: macchiato.fs.path/resolve at line 75 macchiato/fs/path.cljs

**Comment by yogthos** [comment]
Thanks, just pushed out a new release with a fix.

**Comment by kommen** [comment]
Thanks!
